#!/usr/bin/perl -w

# This perl script is used to invoke stilts (if it's installed and the "stilts"
# command properly calls it) to generate a plot of retained mass fraction for
# the different orbits generated by the SALTSA_example.cpp script.

$cmd = "stilts plot2d ofmt=png out='M_ret_full.png' legend=true " .
	"grid=false ylog=false xpix=500 ypix=400 ylo=-0.8 ";

for($i=0;$i<=9;$i++) {
    $cmd = $cmd . "ifmt".$i."=ascii in".$i."=stripping_test_orbital".$i.".dat " .
	"cmd".$i."='addcol log\\(M/M0\\) log10(m_ret)' ydata".$i."=log\\(M/M0\\) " .
	"cmd".$i."='addcol t/P t/8.77683' xdata".$i."=t/P " .
        "shape".$i."=filled_circle " .
	"size".$i."=0 line".$i."=DotToDot "
}

for($i=0;$i<=2;$i++) {
    $cmd = $cmd . "ifmt9".$i."=ascii in9".$i."=stripping_test_orbital1".$i.".dat " .
	"cmd9".$i."='addcol log\\(M/M0\\) log10(m_ret)' ydata9".$i."=log\\(M/M0\\) " .
	"cmd9".$i."='addcol t/P t/8.77683' xdata9".$i."=t/P " .
        "shape9".$i."=filled_circle " .
	"size9".$i."=0 line9".$i."=DotToDot "
}

$cmd = $cmd . "color0=black color1=blue color2=cyan color3=green color4=yellow " .
              "color5=red color6=magenta color7=blue color8=cyan color9=green " .
              "color90=yellow color91=red color92=black ";

$cmd = $cmd . "name0='c=1.00' name1='c=.99' name2='c=.95' name3='c=.9' " .
    "name4='c=.8' name5='c=.7' name6='c=.6' name7='c=.5' name8='c=.4' " .
    "name9='c=.3' name90='c=.2' name91='c=.1' name92='c=.05'";

system($cmd);

